Fixed themeName not found error
BCIT-COMP-4976-Term-Project/plan-your-vote-cda pull request #15
Opened 2020-11-17 22:46 UTC by jvina

2020-11-17 23:05 UTC, ZedTT requested changes, later dismissed
Looks good except that we maybe shouldn't have console logs in mater.

2020-11-17 23:05 UTC, ZedTT commented on src/pages/App/index.jsx
> +    console.log(this.state.images[1].placement)
Do we want console logs in master?

2020-11-17 23:05 UTC, ZedTT commented on src/pages/App/index.jsx
> +
extra newline not that it matters

2020-11-17 23:05 UTC, ZedTT commented on src/pages/App/index.jsx
> +    console.log("images", this.state.images);
Do we want console logs in master?

2020-11-17 23:16 UTC, HaiOliver approved these changes, later dismissed

2020-11-17 23:16 UTC, HaiOliver commented on src/pages/App/index.jsx
> +
ya, it doesnot matter

2020-11-17 23:16 UTC, HaiOliver commented on src/pages/App/index.jsx
> +    console.log("images", this.state.images);
i think she just test

2020-11-24 04:27 UTC, HaiOliver approved these changes, later dismissed

2020-11-24 04:46 UTC, ZedTT approved these changes
LGTM after removing the extra logs. Note that I haven't tested that it runs, and only reviewed the code through the browser. I believe someone else from your team has reviewed this, though.

Let me know if you would prefer that I test the environment before merging, otherwise feel free to merge.

2020-11-24 04:50 UTC, merged